-- Users: application accounts. IDs are generated by the application.
CREATE TABLE users (
    id            uuid PRIMARY KEY,
    email         text NOT NULL,
    password_hash text NOT NULL,
    display_name  text NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

-- Email is normalised to lowercase by the application before insert.
CREATE UNIQUE INDEX uq_users_email ON users (email);

-- Friendships: one row per unordered pair of users covers both directions.
-- requester_id records who sent the request (and stays as the originator
-- after acceptance). status is pending until accepted.
CREATE TABLE friendships (
    id           uuid PRIMARY KEY,
    requester_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    addressee_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status       text NOT NULL CHECK (status IN ('pending', 'accepted')),
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    accepted_at  timestamptz,
    CONSTRAINT friendships_no_self CHECK (requester_id <> addressee_id)
);

-- Symmetric uniqueness: prevents both (A,B) and (B,A) from existing, so a
-- reverse request cannot create a duplicate relationship.
CREATE UNIQUE INDEX uq_friendship_pair ON friendships (
    LEAST(requester_id, addressee_id),
    GREATEST(requester_id, addressee_id)
);
CREATE INDEX idx_friendships_requester ON friendships (requester_id, status);
CREATE INDEX idx_friendships_addressee ON friendships (addressee_id, status);

-- Blocks: directional. blocker_id has blocked blocked_id.
CREATE TABLE blocks (
    id         uuid PRIMARY KEY,
    blocker_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    blocked_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT blocks_no_self CHECK (blocker_id <> blocked_id),
    CONSTRAINT uq_block_pair UNIQUE (blocker_id, blocked_id)
);
CREATE INDEX idx_blocks_blocked ON blocks (blocked_id);
