// The canonical list of programming languages a user can list on their profile
// and filter by. Must stay in sync with the backend's internal/langs/langs.go.
export const PROGRAMMING_LANGUAGES: string[] = [
  "Go",
  "TypeScript",
  "JavaScript",
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Rust",
  "Scala",
  "Dart",
  "Elixir",
  "Erlang",
  "Haskell",
  "Clojure",
  "F#",
  "Objective-C",
  "R",
  "Julia",
  "MATLAB",
  "Perl",
  "Lua",
  "Groovy",
  "Shell",
  "PowerShell",
  "SQL",
  "HTML",
  "CSS",
  "Solidity",
  "Zig",
  "Nim",
  "OCaml",
  "Crystal",
  "Visual Basic",
  "Assembly",
  "COBOL",
  "Fortran",
  "Scheme",
  "Common Lisp",
] as const;
